### PR TITLE
Removed leading whitespaces

### PR DESCRIPTION
**Pull request by Andrew15-5**
```sh
rg -l0 '[ \t]+$' | xargs -0 sd '[ \t]+$' ''
```

### CODE REVIEW

**Comment by johannes-wolf** [comment]
I won't merge this to master, as it would generate unnecessary merge conflicts with `0.2.0`.

**Comment by Andrew15-5** [comment]
Should I instead open my PRs based on `0.2.0` branch?

**Comment by johannes-wolf** [comment]
> Should I instead open my PRs based on `0.2.0` branch?

Yes.

**Comment by Andrew15-5** [comment]
(I re-applied the same command on the new base branch.)

**Comment by johannes-wolf** [comment]
I think you have to rebase again… maybe you forgot to fetch the current 0.2.0?

**Comment by Andrew15-5** [comment]
> I think you have to rebase again… maybe you forgot to fetch the current 0.2.0?

Sorry, I guess I was too sleepy and used `git fetch` or something instead of `git fetch upstream`. And I didn't even flinch about the fact that `0.2.0` branch was very low in the git branch graph. I checked, and last commit was 3 weeks ago, which is not true. But with clear mind, I re-re-applied on the **latest** `0.2.0`'s update/commit.

**Comment by johannes-wolf** [comment]
Outdated.

**Comment by Andrew15-5** [comment]
I can't update it if it's closed.

**Pull request closed without merging**
